// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_identity.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :exec
INSERT INTO auth_identity (user_id, provider, subject, password_hash)
VALUES ($1, $2, $3, $4)
`

type CreateAuthIdentityParams struct {
	UserID       int64
	Provider     string
	Subject      string
	PasswordHash pgtype.Text
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, createAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.PasswordHash,
	)
	return err
}

const getPasswordIdentity = `-- name: GetPasswordIdentity :one
SELECT user_id, password_hash FROM auth_identity
WHERE provider = 'password' AND subject = $1
`

type GetPasswordIdentityRow struct {
	UserID       int64
	PasswordHash pgtype.Text
}

func (q *Queries) GetPasswordIdentity(ctx context.Context, subject string) (GetPasswordIdentityRow, error) {
	row := q.db.QueryRow(ctx, getPasswordIdentity, subject)
	var i GetPasswordIdentityRow
	err := row.Scan(&i.UserID, &i.PasswordHash)
	return i, err
}
