// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invite (team_id, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateInviteParams struct {
	TeamID    int64
	TokenHash []byte
	CreatedBy int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (int64, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TeamID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT i.id, i.team_id, i.expires_at, i.revoked_at, t.name AS team_name
FROM invite i
JOIN team t ON t.id = i.team_id
WHERE i.token_hash = $1
FOR SHARE OF i
`

type GetInviteByTokenHashRow struct {
	ID        int64
	TeamID    int64
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	TeamName  string
}

// FOR SHARE: a revoke waits until an accept that already read the invite
// commits, so an accept never lands after the revoke it raced.
func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash []byte) (GetInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i GetInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.TeamName,
	)
	return i, err
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE invite
SET revoked_at = coalesce(revoked_at, $1)
WHERE id = $2 AND team_id = $3
`

type RevokeInviteParams struct {
	Now    pgtype.Timestamptz
	ID     int64
	TeamID int64
}

// Scoped to the team, so a caller authorized on another team revokes
// nothing. Keeps the first revocation time when called twice.
func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvite, arg.Now, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
