// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMembershipByTeamAndUser = `-- name: GetMembershipByTeamAndUser :one
SELECT id, team_id, user_id, role, status, shirt_number, position, display_name_override, push_muted, created_at FROM membership
WHERE team_id = $1 AND user_id = $2
`

type GetMembershipByTeamAndUserParams struct {
	TeamID int64
	UserID pgtype.Int8
}

func (q *Queries) GetMembershipByTeamAndUser(ctx context.Context, arg GetMembershipByTeamAndUserParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByTeamAndUser, arg.TeamID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.ShirtNumber,
		&i.Position,
		&i.DisplayNameOverride,
		&i.PushMuted,
		&i.CreatedAt,
	)
	return i, err
}
