// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO membership (team_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateMembershipParams struct {
	TeamID int64
	UserID pgtype.Int8
	Role   string
	Status string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMembershipByTeamAndUser = `-- name: GetMembershipByTeamAndUser :one
SELECT id, team_id, user_id, role, status, shirt_number, position, display_name_override, push_muted, created_at FROM membership
WHERE team_id = $1 AND user_id = $2
`

type GetMembershipByTeamAndUserParams struct {
	TeamID int64
	UserID pgtype.Int8
}

func (q *Queries) GetMembershipByTeamAndUser(ctx context.Context, arg GetMembershipByTeamAndUserParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByTeamAndUser, arg.TeamID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.ShirtNumber,
		&i.Position,
		&i.DisplayNameOverride,
		&i.PushMuted,
		&i.CreatedAt,
	)
	return i, err
}

const rejoinMembership = `-- name: RejoinMembership :execrows
UPDATE membership
SET role = 'player', status = 'pending'
WHERE id = $1 AND status = 'left'
`

// A member who left comes back through an invite: the same row, keeping its
// history, number and position (R8.4), as a pending player waiting for an
// admin (R7.2). Only a row that is still `left` changes, so a stale read can
// never demote an active member.
func (q *Queries) RejoinMembership(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, rejoinMembership, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
