// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (user_id, token_hash, created_at, last_used_at, rotated_at)
VALUES ($1, $2, $3, $3, $3)
RETURNING id
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionByPreviousTokenHash = `-- name: GetSessionByPreviousTokenHash :one
SELECT id, user_id, token_hash, previous_token_hash, created_at, last_used_at, rotated_at FROM session WHERE previous_token_hash = $1
`

func (q *Queries) GetSessionByPreviousTokenHash(ctx context.Context, previousTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByPreviousTokenHash, previousTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.PreviousTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, previous_token_hash, created_at, last_used_at, rotated_at FROM session WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.PreviousTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :execrows
UPDATE session
SET previous_token_hash = token_hash,
    token_hash = $1,
    rotated_at = $2,
    last_used_at = $2
WHERE id = $3 AND token_hash = $4
`

type RotateSessionParams struct {
	NewTokenHash []byte
	Now          pgtype.Timestamptz
	ID           int64
	OldTokenHash []byte
}

// Rotation only applies if the session still holds the token the caller
// presented, so two concurrent requests cannot both rotate it.
func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSession,
		arg.NewTokenHash,
		arg.Now,
		arg.ID,
		arg.OldTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE session SET last_used_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID         int64
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastUsedAt)
	return err
}
