// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO team (name, timezone)
VALUES ($1, $2)
RETURNING id, name, timezone, captain_membership_id, created_at
`

type CreateTeamParams struct {
	Name     string
	Timezone string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Timezone)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.CaptainMembershipID,
		&i.CreatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, timezone, captain_membership_id, created_at FROM team
WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.CaptainMembershipID,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveTeamsForUser = `-- name: ListActiveTeamsForUser :many
SELECT t.id, t.name, t.timezone, t.captain_membership_id, t.created_at FROM team t
JOIN membership m ON m.team_id = t.id
WHERE m.user_id = $1 AND m.status = 'active'
ORDER BY t.id
`

func (q *Queries) ListActiveTeamsForUser(ctx context.Context, userID pgtype.Int8) ([]Team, error) {
	rows, err := q.db.Query(ctx, listActiveTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Timezone,
			&i.CaptainMembershipID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTeam = `-- name: LockTeam :one
SELECT id FROM team
WHERE id = $1
FOR NO KEY UPDATE
`

// Serializes every change that can remove an admin from the team (R6.4).
// NO KEY UPDATE still conflicts with itself but not with the KEY SHARE lock
// that foreign-key checks take, so inserts that reference the team (invites,
// matches, charges) are not blocked.
func (q *Queries) LockTeam(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockTeam, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE team
SET name     = coalesce($1, name),
    timezone = coalesce($2, timezone)
WHERE id = $3
RETURNING id, name, timezone, captain_membership_id, created_at
`

type UpdateTeamParams struct {
	Name     pgtype.Text
	Timezone pgtype.Text
	ID       int64
}

// A NULL argument keeps the current value (partial PATCH).
func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.Name, arg.Timezone, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.CaptainMembershipID,
		&i.CreatedAt,
	)
	return i, err
}
