// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package sqlcdb

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO team (name, timezone)
VALUES ($1, $2)
RETURNING id, name, timezone, captain_membership_id, created_at
`

type CreateTeamParams struct {
	Name     string
	Timezone string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Timezone)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.CaptainMembershipID,
		&i.CreatedAt,
	)
	return i, err
}
