// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (name, email, birth_date)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	Name      pgtype.Text
	Email     pgtype.Text
	BirthDate pgtype.Date
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.BirthDate)
	var id int64
	err := row.Scan(&id)
	return id, err
}
